#!/bin/sh

set -e
WORKDIR=$(pwd)

echo "Installing basic build tools"
sudo pacman -S --noconfirm git make binutils gcc pkg-config fakeroot

if [ "$(which yaourt)" == "" ]
then
    echo "Installing yaourt to fetch some packages from AUR"
    cd /tmp
    git clone https://aur.archlinux.org/package-query.git
    cd package-query
    makepkg -si --noconfirm
    cd ..
    git clone https://aur.archlinux.org/yaourt.git
    cd yaourt
    makepkg -si --noconfirm
    cd ${WORKDIR}
    yaourt -Syy
fi

# Fix glib2 build
export PYTHONPATH="/usr/share/glib-2.0"
echo "Fetching necessary files to build perl modules for Slic3r"
yaourt -S --noconfirm  gtk2 \
                       wxgtk2 \
                       perl-module-build \
                       perl-net-dbus \
                       perl-extutils-cppguess \
                       perl-extutils-xspp \
                       perl-devel-checklib \
                       perl-wx-constructors \
                       expat \
                       cpanminus \
                       libxmu \
                       freeglut \
                       curl \
                       boost \
                       bison \
                       flex \
                       patch \
                       python-codegen \
                       python2-codegen

CPAN=$(find / -name cpanm 2> /dev/null |head -n1)

sudo ${CPAN} Boost::Geometry::Utils \
        local::lib \
        Math::Clipper \
        Math::ConvexHull \
        Math::ConvexHull::MonotoneChain \
        Math::Geometry::Voronoi \
        Math::PlanePath \
        Moo

if [ -f /.dockerenv ]
then
    WX_BUILD_OPTION="--notest"
else
    WX_BUILD_OPTION=""
fi
sudo ${CPAN} ${WX_BUILD_OPTION} Wx

if [ ! -d Slic3r ]
then
    echo "Downloading Slic3r sources"
    git clone https://github.com/alexrj/Slic3r.git
    cd Slic3r
    git checkout -b origin/master
else
    echo "Using Slic3r local sources"
    cd Slic3r
fi

echo "Building Slic3r.."
export PATH=/usr/bin/vendor_perl:$PATH
perl Build.PL
perl Build.PL --gui
cd ..
